app1/urls.py
from django.urls import path
from app1.views import *
app_name='vk'
urlpatterns = [
    path('vamsi/',vamsi,name='vamsi'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='pj'
urlpatterns=[path('poojitha/',poojitha,name='poojitha')]

vo6/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.urls import *
from app2.urls import *
urlpatterns = [
    path('admin/', admin.site.urls),path('app1/',include('app1.urls')),path('app2/',include('app2.urls')),
]
#http://127.0.0.1:8000/app1/vamsi/

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def vamsi(request):
    return render(request,'h1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def poojitha(request):
    return render(request,'h2.html')

templates/h1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/c1.css' %}">
</head>
<body>
    <center>
        <h1>HELLO</h1>
        <a href="{% url 'pj:poojitha' %}"><h2>Poojitha</h2></a>
        <br>
        <img src="{% static 'img/a.jpg' %}" alt="AI" width="1080px" height="1080px">

    </center>


</body>
</html>

templates/h2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/c2.css' %}">
</head>
<body>
    <center>
        <h1>HELLO</h1>
        <a href="{% url 'vk:vamsi' %}"><h2>VamsiKrishna</h2></a>
        <br>
        <img src="{% static 'img/b.jpg' %}" alt="UV" width="1080px" height="1080px">
    </center>
</body>
</html>